services:
  - type: web
    name: bhashasetu-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
